/** @type {import('next').NextConfig} */

// Base URL of the logged-in application (now on its own subdomain).
const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://app.auto1source.com';

/**
 * Old links that used to live on the main domain (auto1source.com) but actually
 * belong to the application must now redirect to app.auto1source.com.
 *
 * These are the application's own route namespaces — the marketing site does NOT
 * use any of them, so there is no collision with marketing pages such as
 * /customers, /employees, /parts or /marketing.
 *
 * NOTE FOR INFRA / Bao: confirm this list against the application's full route
 * table before go-live. Add any additional customer-facing deep links here.
 */
const APP_ROUTE_PREFIXES = [
  // Role login / sign-up entry points
  'owner',
  'employee',
  'vendor',
  'customer',
  'advertisement',
  // Customer-facing deep links generated by the app (payments, agreements, docs)
  'agreement',
  'pay',
  'workorder',
  'upload',
  'docs',
  'mobile-payment',
  'payment',
  'video',
  // Internal app screens
  'in-shop',
  'payroll',
  'preferences',
];

const nextConfig = {
  reactStrictMode: true,

  // This project sits beside other repos with their own lockfiles; pin the
  // file-tracing root to this folder so Next doesn't infer a parent directory.
  outputFileTracingRoot: __dirname,

  async redirects() {
    return APP_ROUTE_PREFIXES.map((prefix) => ({
      source: `/${prefix}/:path*`,
      destination: `${APP_URL}/${prefix}/:path*`,
      permanent: true,
    })).concat(
      // Also redirect the bare prefix (e.g. /payment with no sub-path)
      APP_ROUTE_PREFIXES.map((prefix) => ({
        source: `/${prefix}`,
        destination: `${APP_URL}/${prefix}`,
        permanent: true,
      }))
    );
  },
};

module.exports = nextConfig;
